#!/usr/bin/env python

import sys

from packages.Handout import Handout
from packages.Messages import messages



def main():
    page = sys.argv[1] if len(sys.argv) > 1 else "index"
    handout = Handout(page)

    if not messages.ok:
        sys.exit(1)

    handout.write()
    handout.compile()

if __name__ == "__main__":
    main()
